### ISSUE TITLE
Buttons not always visible when it should be there

### ISSUE THREAD

**Issue by RonStoop** [tieniber/ShowMore#2] opened 2017-05-10 13:44 UTC
The widget is not working correctly all the time. Sometimes the text is cutted off, but there is no 'show more' button. Inspect the element via the browser shows that the button has a class 'hidden'. Removing this class does show the button and pressing the button does result in more text.

Also sometimes the button 'show less' is shown, while the text doesn't exceed the maximum number of characters. Pressing the button doesn't result in less text as well.

I have tried the figure out any consequent circumstance when the widget fails, but so far I found nothing.

**Comment by tieniber** [comment] 2017-07-24 21:55
I cannot reproduce this issue. I did just commit a few minor code edits that perhaps could fix your issue.

 - an !important to the CSS so that the hidden class will be respected
 - a fix so that shortening and then lengthening the string correctly removes and re-shows the 'show more' link

Please let me know if this works for you. I am going to close this issue, but please comment or open a new one if you can reproduce the issue

**Closed as completed by tieniber** 2017-07-24 21:55 UTC

**Comment by RonStoop** [comment] 2017-08-07 10:43
It looks like the fixes solved my problems as well.
Do you update the new version in de AppStore as well? Otherwise, I will download it in a new project with the errors.

Thanks!

**Comment by tieniber** [comment] 2017-08-07 19:45
I'll submit the updated version to the app store today, but it will probably take a few days for it to be approved.

**Comment by tmisker** [comment] 2018-10-24 12:49
> I'll submit the updated version to the app store today, but it will probably take a few days for it to be approved.

Hmm, I have similar issues... It has been over a year now, is it approved? ;)
